config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    get 'home', to: 'static_pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do
      resources :words
    end
  end
  root 'static_pages#home'

  get 'static_pages/about'
  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  resources :relationships, only:[:create,:destroy]
  resources :categories, only:[:index]
  resources :words, only: [:index]

  resources :lessons, only:[:create,:show] do 
    resources :answers, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :choices
  validates :content, presence: true
  validate :has_one_correct_answer
  validate :has_unique_choice

  def correct_answer
    choices.find_by(correct: true).content
  end

  def has_one_correct_answer
    if choices.select{|choice| choice.correct }.length != 1
      return errors.add :base,"Must have one correct answer!"
    end
  end

  def has_unique_choice
    if choices.uniq{|choice| choice.content }.length != 3
      return errors.add :base,"Each choices must be unique!"
     end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  def index
    @category = Category.find(params[:category_id])
    @words = @category.words.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build
    3.times{@word.choices.build}
  end
  
  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.build(word_params)
    if @word.save
      flash[:success] = "Successfully created words!"
      redirect_to admin_category_words_url
    else
      render'new'
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    if @word.update_attributes(word_params)
      flash[:success] ="Successfully updated!"
      redirect_to admin_category_words_url
    else
      render 'edit'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    flash[:danger] ="You deleted a category!"
    redirect_to admin_category_words_url
  end
 



  private
    def word_params
      params.require(:word).permit(:content, choices_attributes: [:id, :content, :correct])
    end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :logged_in_user
  
  def index
    @answers = current_user.answers.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @category, @word] do |f|%>
    <%= render 'shared/error_messages',object: f.object%>
    <div class="form-group">
        <%= label_tag "Word" %>
        <%= f.text_field :content, class: "form-control" %>
        <hr>
    </div>
    <div class ="form-group">
        <%= label_tag "Choices"%>
        <%= f.fields_for :choices do |choice|%>
            <%= choice.text_field :content, class:"form-control"%>
            <%= choice.check_box :correct, class:"d-inline"%>
            <p class="d-inline">This is the correct answer</p>
        <% end%>
        <%= f.submit msg, class:"btn btn-primary btn-block mb-3 "%>
    </div>
<% end %>

app/views/admin/words/edit.html.erb
<div class="form content">
    <h1 class="text-center">Edit word</h1>
    <div class="container col-6 m-auto">
        <%= render'form' ,msg: "Save change"%>
        <%= link_to "Back",admin_category_words_path,class:"btn btn-outline-secondary btn-block"%>
    </div>
</div>

app/views/admin/words/index.html.erb
<div class="col-8 m-auto text-center">
    <h1>Administrate Words</h1>
    <div class="pagination justify-content-center mt-4">
        <%= will_paginate %>
    </div>
    <div class="row">
        <div class="col-6">
            <h2><%= @category.title %></h2>
            <h5><%= @category.description %></h5>
        </div>
        <div class="col-6">
            <%= link_to "Create word", new_admin_category_word_path, class: "btn btn-primary" %>
         </div>
    </div>
    <div class="row">
    <% if @words.any? %>
        <table class="table mt-4">
            <thead>
            <tr>
                <th scope="col">Word</th>
                <th scope="col">Answer</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @words.each do |word|%>
                <tr>
                    <td><%= word.content %></td>
                    <td><%= word.correct_answer%></td>
                    <td>
                        <%= link_to "Edit",edit_admin_category_word_path(@category,word),class:"btn btn-outline-primary btn-block"%>
                        <%= link_to "Delete",admin_category_word_path(@category,word),method: :delete, data: {confirm: "Are you sure to delete word?"}, class:"btn btn-outline-secondary btn-block"%>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
    <%else%>
        <h3 class="mx-auto">There is no words</h3>
    <%end%>
    </div>
     <div class="pagination justify-content-center mt-4">
        <%= will_paginate %>
    </div>
    <%= link_to "Back",admin_categories_path,class:"btn btn-outline-secondary px-5 mb-4"%>
</div>

app/views/admin/words/new.html.erb
<div class="form content">
    <h1 class="text-center">Create word</h1>
    <div class="container col-6 m-auto">
        <%= render'form' ,msg: "Create word"%>
        <%= link_to "Back",admin_category_words_path,class:"btn btn-outline-secondary btn-block"%>
    </div>
    
</div>