config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    get 'home', to: 'static_pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do
      resources :words
    end
  end
  root 'static_pages#home'

  get 'static_pages/about'
  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  resources :relationships, only:[:create,:destroy]
  resources :categories, only:[:index]
  resources :words, only: [:index]

  resources :lessons, only:[:create,:show] do 
    resources :answers, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length:{ maximum: 100}
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :logged_in_user
  before_action :admin_user 

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)    # Not the final implementation!
    if @category.save
      flash[:success] ="You successfully made the category! "
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end  

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end
 
  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] ="Successfully updated!"
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:danger] ="You deleted a category!"
    redirect_to admin_categories_url
  end
 
  private
    def category_params
      params.require(:category).permit(:title, :description)
    end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :logged_in_user

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
    @status = params[:status]

    if @status == "1"
      @categories = current_user.categories.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
    elsif @status = "0"
      @categories = @categories.where.not(id: current_user.category_ids).paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
    end
  end


end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f|%>
    <%= render 'shared/error_messages',object: f.object%>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.submit msg , class: "btn btn-block btn-primary mt-4" %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="form content">
    <h1 class="text-center">Edit category</h1>
    <div class="container col-6 m-auto">
        <%= render'form', msg: "Update category"%>
        <%= link_to "Back",admin_categories_path,class:"btn btn-outline-secondary btn-block"%>
    </div>
    
</div>

app/views/admin/categories/index.html.erb
<div class="col-8 m-auto text-center">
    <h1>Administrate Categories</h1>
    <%= link_to "Create category", new_admin_category_path, class: "btn btn-primary" %>
        <div class="pagination justify-content-center mt-4">
            <%= will_paginate %>
        </div>
        <div class="row">
        <% if @categories.any? %>
            <table class="table mt-4">
                <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category|%>
                    <tr>
                        <td><%= link_to category.title, admin_category_words_path(category)%></td>
                        <td><%= category.description %></td>
                        <td>
                            <%= link_to "Edit",edit_admin_category_path(category),class:"btn btn-outline-primary btn-block"%>
                            <%= link_to "Delete",admin_category_path(category),method: :delete, data: {confirm: "Are you sure to delete category?"}, class:"btn btn-outline-secondary btn-block"%>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
        <% else %>
            <h3 class="mx-auto">There is no category.</h3>
        <% end %>
        </div>
        <div class="pagination justify-content-center mt-4">
            <%= will_paginate %>
        </div>
    <%= link_to "Back",admin_home_path,class:"btn btn-outline-secondary px-5 mb-4"%>
</div>

app/views/admin/categories/new.html.erb
<div class="form content">
    <h1 class="text-center">Create category</h1>
    <div class="container col-6 m-auto">
        <%= render'form'%>
        <%= link_to "Back",admin_categories_path,class:"btn btn-outline-secondary btn-block"%>
    </div>
    
</div>