config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
    get 'home', to: 'static_pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do
      resources :words
    end
  end
  root 'static_pages#home'

  get 'static_pages/about'
  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  resources :relationships, only:[:create,:destroy]
  resources :categories, only:[:index]
  resources :words, only: [:index]

  resources :lessons, only:[:create,:show] do 
    resources :answers, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length:{ maximum: 100}
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :logged_in_user
  before_action :admin_user 

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)    # Not the final implementation!
    if @category.save
      flash[:success] ="You successfully made the category! "
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end  

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end
 
  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] ="Successfully updated!"
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:danger] ="You deleted a category!"
    redirect_to admin_categories_url
  end
 
  private
    def category_params
      params.require(:category).permit(:title, :description)
    end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :logged_in_user

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
    @status = params[:status]

    if @status == "1"
      @categories = current_user.categories.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
    elsif @status = "0"
      @categories = @categories.where.not(id: current_user.category_ids).paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
    end
  end


end

app/views/categories/index.html.erb
<div class="col-8 m-auto text-center">
    <h1>Categories</h1>
        <%= link_to "All",categories_path,class:"btn btn-outline-primary filtering #{'active' if  params[:status] == nil}"%>
        <%= link_to "Learned",categories_path(status: "1"),class:"btn btn-outline-primary filtering #{'active' if  params[:status] == "1"}"%>
        <%= link_to "Not learned",categories_path(status: "0"),class:"btn btn-outline-primary filtering #{'active' if  params[:status] == "0"}"%>
        <div class="pagination justify-content-center mt-4">
            <%= will_paginate %>
        </div>
        <div class="row">
        <% if @categories.any? %>
                <% @categories.each do |category|%>
                <div class="col-6">
                    <div class="card mx-2 my-2">
                        <div class="card-header">
                            <h5 class="card-title"><%= link_to category.title,"#",class:"float-left"%></h5>
                            <div class="stats float-right">
                                <strong class="stat">
                                    <%= pluralize(category.words.count,"Word") %>
                                </strong>
                            </div>
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-muted float-left"><%= category.description %></h6>
                            <% lesson = current_user.lesson_taken(category.id)%>
                            <% if lesson.nil? %>
                                <%=link_to "Start Lesson",lessons_path(category_id: category.id),method: :post,class:"float-right btn btn-outline-secondary"%>
                            <% else %>
                                <%=link_to "Show Result",lesson_path(lesson),class:"float-right btn btn-outline-primary"%>
                            <% end %>
                        </div>
                        
                    </div>
                </div>
                <% end %>
        <% else %>
            <h3 class="mx-auto">There is no category.</h3>
        <% end %>
        </div>
        <div class="pagination justify-content-center mt-4">
            <%= will_paginate %>
        </div>
    <%= link_to "Back","#",class:"btn btn-outline-secondary px-5 mb-4"%>
</div>